name: GnomeSteal
version: '${project.version}'
main: me.minignomer.gnomesteal.GnomeSteal
api-version: 1.19
authors: [ MiniGnomer ]
description: Gnome = Life
commands:
  withdraw:
    description: Withdraws a heart from your health bar and turns it into a heart item.
    usage: /<command> <number of hearts>
  gsconfig:
    description: Allows you to configure the GnomeSteal plugin with commands.
    usage: /<command> <config> <other arguments>
    permission: gnomesteal.config
    aliases:
      - gsc
      - gnomestealconfig
      - gnomestealc
